# Name your workflow
name: CI

# Set on which events you want run the actions
on:
  pull_request:  
    branches: [ master ]

jobs:
  # This workflow contains a job called "integration"
  integration:

    # A strategy that defines different variations of an environment to run each job in.
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node-versions: [ 18.x ]

    # The runners that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build production project
        run: npm run build:prod
        if: always()
      - name: linting typescript
        run: npm run lint:ts
        if: always()
      - name: linting css
        run: npm run lint:scss
        if: always()
      - name: unit testing
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      - name: screenshot testing
        run: npm run test:ui:ci
        if: always()